FROM node:14.6
WORKDIR /app

# Важно для кеширования слоев
COPY ./app/package.json package.json
COPY ./app/package-lock.json package-lock.json
COPY Makefile Makefile

RUN npm install
RUN npm install pg --save

COPY ./app .
ENTRYPOINT npm start
