version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: lov3catch/devops1
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command: npm test