version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    expose:
      - 8080
    depends_on:
      - db
    volumes:
      - ./project:/app
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD:/srv
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
    external: true
  caddy_config:

