FROM node:14.6
WORKDIR /app

# Важно для кеширования слоев
COPY ./project/package.json package.json
COPY ./project/package-lock.json package-lock.json
COPY /Makefile Makefile

RUN npm install
RUN npm install pg --save

COPY ./project .
ENTRYPOINT npm start
