version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    expose:
#      - 8080
    tty: true
    depends_on:
      - db
    volumes:
      - .:/app
#  caddy:
#    image: caddy
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#    expose:
#      - 80
#      - 443
#    volumes:
#      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
#      - $PWD:/srv
