version: '3'
#services:
#  app:
#    build: .
#    tty: true
#    depends_on:
#      - db
#    volumes:
#      - .:/app
#    ports:
#      - "8080:8080"
#    expose:
#      - 8080
#  caddy:
#    image: caddy
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#    expose:
#      - 80
#      - 443
#    volumes:
#      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
#      - $PWD:/srv
