version: '3'
services:
  app:
    build: .
    tty: true
    volumes:
      - .:/app
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD:/srv
